apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: haider665/blog:v4
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "1280Mi"
              cpu: "500m"
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: oap:11800
            - name: SW_AGENT_NAME
              value: blog

---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: NodePort
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30200
